shopsite/favorites/urls.py
from django.urls import path, include
from .views import *

app_name ='favorites'

urlpatterns = [ 
    path('favorites', include([
    path('<id>/add/', add_to_favorites, name = 'add'),
    path('<id>/remove/', remove_from_favorites, name='remove'),
    path('delete/', delete_favorites, name='delete'),
    ])),
    ]
# urlpatterns =  [
#     path('<id>/add/', add_to_favorites, name = 'add'),
#     path('<id>/remove/', remove_from_favorites, name='remove'),
#     path('delete/', delete_favorites, name='delete'),
#     ]
    

shopsite/shopapp/urls.py
from django.urls import path, include
from .views import *
from django.views.decorators.cache import cache_page
from .router import router


# добавить адреса для представлений форм 
urlpatterns = [
    path('', Home.as_view(), name='home'), # соответсвует маршруту http://127.0.0.1:8000/
    path('item/<slug:item_slug>', ShowItem.as_view(), name='item'),
    # path('profile/<slug:username>/', ProfileView.as_view(), name='profile'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('category/<slug:categ_slug>/', cache_page(60)(Categories.as_view()), name ='category'),
    path('request/', RequestItem.as_view(), name='request'),
    path('additem/', AddItem.as_view(), name='add_item'),
    path('contact/', contact, name='contact'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('edit_profile/', ProfileEditView.as_view(), name='edit_profile'),
    path('password/', ChangePasswordView.as_view(), name='password'),
    path('about/', cache_page(6000)(AboutView.as_view()), name='about'),
    path('favorite_list/', FavoriteLiist.as_view(), name='favor_list'),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),


]

shopsite/shopsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from shopsite import settings
from shopapp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls')),
    path('', include('favorites.urls')),
    path('captcha/', include('captcha.urls')),
]

from django.conf.urls.static import static

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

shopsite/shopapp/models.py
from django.db import models
from django.core import validators
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Item(models.Model):
    '''
    Основная модель для товаров сайта
    '''
    title = models.CharField(max_length=300, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    size = models.CharField(max_length=200, verbose_name='Размер')
    price = models.FloatField(validators = [validators.MinValueValidator(0)], default=0, verbose_name='Цена')
    count = models.IntegerField(validators = [validators.MinValueValidator(0)], default=1, verbose_name='Количество')
    discount = models.FloatField(validators= [validators.MinValueValidator(0)], default=0, verbose_name='Скидка')
    available = models.BooleanField(default=True, verbose_name='Наличие')
    brand = models.CharField(max_length=200, verbose_name='Бренд')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    categ = models.ForeignKey('Category', on_delete=models.DO_NOTHING, verbose_name='Категория', related_name='categ')    

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('item', kwargs={'item_slug': self.slug})


class Category(models.Model):
    '''
    Модель для категорий товаров
    '''
    name = models.CharField(max_length=255, db_index=True, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'categ_slug': self.slug})


class ItemPhoto(models.Model):
    '''
    Отдельная модель для реализации загрузки нескольких фото через одно поле
    '''
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name='Фото')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name='Товар', related_name='photos', db_index=True)
    # related_name='photos' используется для обращения к этому полю через класс Item (for photo in item.photos)
    class Meta:
        verbose_name = 'Фото'
        verbose_name_plural = 'Фотографии'
        
    def __str__(self):
        return self.item.title
    
    def get_absolute_url(self):
        return reverse('photo', kwargs={'photo_pk': self.pk})

# представление для формы запроса товара
class RequestedItem(models.Model):
    '''
    Модель для товаров запрошенных обычными пользователями
    '''
    title = models.CharField(max_length=300, verbose_name='Наименование')
    comments = models.TextField(verbose_name='Комментарии', blank=True)
    size = models.CharField(max_length=50, verbose_name='Размер')
    count = models.IntegerField(validators = [validators.MinValueValidator(0)], default=1, verbose_name='Количество')
    url = models.URLField(blank=True, verbose_name='Ссылка')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время создания заявки')
    categ = models.ForeignKey('Category', on_delete=models.DO_NOTHING, verbose_name='Категория')
    photo = models.ImageField(upload_to="photos_requested/%Y/%m/%d/", verbose_name='Фото', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('request', kwargs={'user_pk': self.pk})

shopsite/shopapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView, CreateView, TemplateView
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.views.generic.edit import UpdateView
from django.contrib.auth import login, logout
from datetime import datetime, timedelta
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView

from .models import *
from .utils import ItemAPIListPagination, DataMixin, menu
from .form import *

from rest_framework import viewsets
from .serializers import *
from .permissions import IsAdminOrReadOnly




class Home(DataMixin, ListView):
    '''
    Главная страница. 
    Отображает список последних поступлений 
    '''
    model = Item
    template_name = 'shop/index.html'
    context_object_name = 'items'

    def get_context_data(self, *, object_list=None, **kwargs):
        cont = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Главная страница")
        return {**cont, **c_def}
    
    def get_queryset(self):
        # фильтр который выводит товары добавленные за последний месяц
        last_month = datetime.now() - timedelta(days=30)
        return Item.objects.filter(time_update__gte=last_month).prefetch_related('photos').select_related('categ')
        

class Categories(DataMixin, ListView):
    '''
    Выводит список товаров по категориям.
    '''
    model = Item
    template_name = 'shop/categories.html'
    context_object_name = 'items'

    def get_context_data(self, **kwargs) -> dict:
        cont = super().get_context_data(**kwargs)
        c = Category.objects.get(slug=self.kwargs['categ_slug'])
        c_def = self.get_user_context(title='Категория - ' + str(c.name), cat_selected=c.pk)
        return {**cont, **c_def}
    
    def get_queryset(self):
        return Item.objects.filter(categ__slug=self.kwargs['categ_slug']).prefetch_related('photos', 'photos__item').select_related('categ')
        
        # ниже была попытка оптимизировать запросы, чтобы получить первые фото товаров сразу, а не в цикле шаблона.
        # item_ids = Item.objects.filter(categ__slug=self.kwargs['categ_slug']).values_list('id', flat=True)
        # item_photos_subquery = ItemPhoto.objects.filter(item_id__in=item_ids).order_by('item_id', 'id').values('item_id', 'photo')
        # subquery_dict = {}
        # for item_id, photo in item_photos_subquery:
        #     if item_id not in subquery_dict:
        #         subquery_dict[item_id] = photo
        # queryset = Item.objects.filter(categ__slug=self.kwargs['categ_slug']).annotate(first_photo=Subquery(subquery_dict.values(), output_field=models.ImageField()))
        # return queryset
    
class ShowItem(DataMixin, DetailView):
    '''
    Детальное представление товара
    '''
    model = Item
    template_name = 'shop/item.html'
    context_object_name = 'item'
    slug_url_kwarg = 'item_slug'

    
    def get_context_data(self, **kwargs) -> dict:
        '''
        Переопределяем контекст, для добавления в него элементов для главного и бокового меню из класса DataMixin
        А так же добавляем вычисляемое значение price_with_discount 
        '''
        cont = super().get_context_data(**kwargs)
        # в контектс добавляем вычисляеое значение цены со скидкой
        item = cont['item']
        item.price_with_discount = item.price - (item.price * (item.discount/100))
        cont['price_with_discount'] = item.price_with_discount

        # проверка, добавлен ли продукт в избранное для вывода нужной кнопки меню
        is_notfavorite = {'id': str(item.id)} not in self.request.session.get('favorites', [])
        # print('session:', self.request.session.get('favorites', []))
        # print('is_notfavorite:', is_notfavorite)
        
        cont['is_notfavorite'] = is_notfavorite
        c_def = self.get_user_context(title=cont['item'])
        return {**cont, **c_def}

   

# представление формы для запроса пользователем некоторого товара
# доработать представление 
class RequestItem(LoginRequiredMixin, DataMixin, CreateView):
    '''
    Представление формы для запроса товара обычным пользователем. 
    Связан с отдельной моделью
    '''
    form_class = RequestItemForm
    template_name = 'shop/request.html'
    raise_exception = True

    def get_context_data(self, **kwargs) -> dict:
        cont = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Запрос товара')
        return {**cont, **c_def}

class AddItem(DataMixin, CreateView):
    '''
    Представления формы для добавления товара на сайт пользователем с правами администратора или работника
    '''
    template_name = 'shop/additem.html'
    form_class = AddItemForm
    form_photos_class = AddPhotoForm
    model = Item
    raise_exception = True

    # def get(self, request):
    #     '''
    #     переопределяем метод гет для передачи двух форм в контекст
    #     '''
    #     form = self.form_class()
    #     form_photos = self.form_photos_class()
    #     return render(request, self.template_name, {'form': form, 'form_photos': form_photos})
    
    def post(self, request):
        '''
        Переопределяем метод пост для сохранения полученных данных в соответсвующие ДБ
        '''
        form = self.form_class(request.POST)
        form_photos = self.form_photos_class(request.POST, request.FILES)
        # if form.is_valid() and form_photos.is_valid():
        if form.is_valid():
            item = form.save()
            for photo in self.request.FILES.getlist('photos'):
                ItemPhoto(photo=photo, item=item).save()
            return HttpResponseRedirect('/')
        return render(request, self.template_name, {'form': form, 'form_photos': form_photos})

    def get_context_data(self, **kwargs) -> dict:
        cont = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Добавление товара')
        cont['form'] = self.form_class
        cont['form_photos'] = self.form_photos_class
        return {**cont, **c_def}

class RegisterUser(DataMixin, CreateView):
    '''
    Представление формы регистрации пользователя
    '''
    form_class = RegisterUserForm
    template_name = 'shop/register.html'
    success_url = reverse_lazy('login')
 
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Регистрация")
        return {**context, **c_def}
    
    def form_valid(self, form):
        '''
        Он отрабатывает при успешной проверки формы регистрации, а значит, при успешной регистрации. 
        Здесь мы самостоятельно сохраняем форму (добавляем пользователя в БД), 
        а затем, вызываем стандартную функцию фреймворка Django login для авторизации пользователя. 
        После этого, делаем перенаправление на главную страницу.
        '''
        user = form.save()
        login(self.request, user)
        return redirect('home')
    

class LoginUser(DataMixin, LoginView):
    '''
    Представление формы авторизации пользователя
    '''
    form_class = LoginUserForm
    template_name = 'shop/login.html'
 
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Авторизация")
        return {**context, **c_def}

    def get_success_url(self):
        return reverse_lazy('home')

class ProfileEditView(DataMixin, LoginRequiredMixin, UpdateView):
    '''
    Представление отображает форму для изменения данных пользователя
    '''
    model = User
    form_class = ProfileEditForm
    template_name = 'shop/edit_profile.html'
    
    change_password = {'title': "Изменение пароля", 'url_name': 'password'}
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Редактирование профиля")
        context['change_password'] = self.change_password
        return {**context, **c_def}
    
    def get_object(self, queryset=None):
        return self.request.user
    
    def get_success_url(self):
        return reverse_lazy('profile')



def logout_user(request):
    '''
    Представлени для разлогирования пользователя на основе базовой функции джанго
    '''
    logout(request)
    return redirect('login')



class ProfileView(DataMixin, LoginRequiredMixin, DetailView):
    '''
    Отображает профиль пользователя
    '''
    model = User
    template_name = 'shop/profile.html'
    context_object_name = 'profile'
    edit = {'title': "Редактирование профиля", 'url_name': 'edit_profile'}

    def get_context_data(self, **kwargs) -> dict:
        cont = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Просмотр профиля')
        cont['edit'] = self.edit
        return {**cont, **c_def}
    
    
    def get_object(self, queryset=None):
        return self.request.user


class ChangePasswordView(DataMixin, LoginRequiredMixin, PasswordChangeView):
    '''
    Для формы изменения пароля
    '''
    form_class = ChangePasswordForm
    success_url = reverse_lazy('profile')
    template_name = 'shop/password.html'
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Изменение пароля")
        return {**context, **c_def}



class AboutView(TemplateView):
    '''
    Страничка о нас.
    '''
    template_name = 'shop/about.html'
    
    menu = [
        {'title': "Обратная связь", 'url_name': 'contact'},
        ]
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user_menu = menu.copy()
        context['menu'] = user_menu

shopsite/shopapp/templates/shop/about.html
{% extends 'shop/base.html' %}

{% block content %}
<h1>О нас</h1>
<p>
    На нашем сайте вы можете найти обувь, одежду и другие товары, купленные из магазинов Европы и Америки
</p>
<p>
    Вы может запросить товар при помощи кнопки верхнего меню "Оставить заявку на товар"
</p>
<p>
    Все товары, которые вы видите в нашем каталоге являются 100% оригиналом
</p>
<div class="contacts">
    <h2>Наши контакты</h2>
    <p><b>WhatsApp:</b> +7999999999</p>
    <p><b>e-mail:</b> <e-mail>egiaz@yandex.ru</e-mail></p>
</div>
<ul class="share-about">
    <li>
        <p>Наш канал на YouTube</p>
        <a class="share-yut" href="https://www.youtube.com/" target="_blank" rel="nofollow"></a>

        <p>Наш телеграм бот</p>
        <a class="share-tg" href="https://t.me/ourcatalogsbot/" target="_blank" rel="nofollow"></a>
    </li>
</ul>

{% endblock %}

shopsite/shopapp/templates/shop/additem.html
{% extends 'shop/base.html' %}

{% block content %}
<form action="{% url 'add_item' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    
    {% for photo in form_photos %}
        <p><label class="form-label" for="{{ photo.id_for_label }}">{{photo.label}}: </label>{{ photo }}</p>
        
    {% endfor %}



    <button type="submit">Отправить заявку</button>
</form>
{% endblock %}

shopsite/shopapp/templates/shop/base.html
{% load static %}
<!-- тег для включенных тегов -->
{% load shop_tags %}
<!-- тег для кеширования -->


<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>
    <link type="text/css" href="{% static 'shop/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="{% static 'shop/images/main.ico' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static user_stylesheet %}" media="screen">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>

    <!-- добавить функционал добавления товара, так чтобы кнопка была видна только работникам и администратору -->
{% block mainmenu %}
    <div class="header">
        <ul id="mainmenu" class="mainmenu">
        <li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>

        {% for m in menu %}
            <li><a href="{% url m.url_name %}">{{m.title}}</a></li>
        {% endfor %}
        {% if request.user.is_authenticated and not request.user.is_staff %}
            <li><a href="{% url 'contact' %}">Обратная связь</a></li>
        {% endif %}
        
        {% if request.user.is_staff %}
            <li><a href="{% url 'add_item' %}">Добавить товар</a></li>
        {% elif request.user.is_authenticated and not request.user.is_staff %}
            <li><a href="{% url 'request' %}">Оставить заявку на товар</a></li>
        {% endif %}

        {% if request.user.is_authenticated %}
            <li class="last"><a href="{% url 'profile' %}">{{user.username}}</a> | <a href="{% url 'logout' %}">Выйти</a></li>
        {% else %}
            <li class="last"><a href="{% url 'register' %}">Регистрация</a> | <a href="{% url 'login' %}">Войти</a></li>
        {% endif %}


        </ul>
        <div class="clear"></div>
	</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->


    <td valign="top" class="left-chapters">
    <ul id="leftchapters">
    
        <li><a href="{% url 'home' %}">Новые поступления</a></li>
        
        {% show_categories cat_selected=cat_selected %}
    
        <li class="share">
            <p>Наш канал</p>
            <a class="share-yt" href="https://www.youtube.com/" target="_blank" rel="nofollow"></a>
		</li>
        <li class="share">
            <p>Наш телеграм бот</p>
            <a class="share-tg" href="https://t.me/ourcatalogsbot/" target="_blank" rel="nofollow"></a>
        </li>

        {% if usd %}
            <div class="valute-bar">
                <p>Курс доллара: {{ usd }}</p>
                <p>Курс евро: {{ eur }}</p>
            </div>
        {% endif %}
	</ul>
</td>

<!-- Конец Sidebar'а -->

<td valign="top" class="content">


{% block content %}
{% endblock %}


<!-- Блок пагинации страницы -->
<!-- проверяем не является ли страница единственной, чтобы зря не отображать пагинацию -->
{% if page_obj.has_other_pages %}
<nav class="list-pages">
    <ul>
		
    <!-- если страница не первая, то отображаем переход на предыдущую страницу  -->
	{% if page_obj.has_previous %}
        <!-- переход на 1-ю страницу -->
        <li class="page-num">
            <a href="?page=1">&lt;&lt;</a>
        </li>
        <!-- переход на следующую страницу -->
        <li class="page-num">
            <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
        </li>
	{% endif %}
    {% for p in paginator.page_range %}
        <!-- блок иф проверяет, если мы на текущей странице, то номер страницы отображать как текст не как ссылку -->
        {% if page_obj.number == p %}
            <li class="page-num page-num-selected">{{ p }}</li>
            <!-- здесь проверяем если р не является текущей страницей и попадает в диапазон, то есть больше либо равен номер минус 2 и меньше либо равен номер + 2 -->
                {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}
            <li class="page-num">
                <!-- то отображаем номер страницы -->
                <a href="?page={{ p }}">{{ p }}</a>
            </li>
        {% endif %}
    {% endfor %}
    <!-- добавляем кнопку перехода на следующую страницу -->
	{% if page_obj.has_next %}
        <li class="page-num">
            <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
        </li>
        <!-- кнопка для перехода на последнюю страницу -->
        <li class="page-num">
            <a href="?page={{ paginator.num_pages }}">&gt;&gt;</a>
        </li>
    {% endif %}
    </ul>
</nav>
{% endif %}
<!-- Конец блока пагинации страницы -->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2021 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
	</div>

</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>

shopsite/shopapp/templates/shop/categories.html
{% extends 'shop/base.html' %}


{% block content %}

<ul class="list-articles">
    {% for item in items %}
    <li> 
        <div class="article-panel">
        <p class="last">Дата добавления: {{item.time_update|date:"d-m-Y H:i:s"}}</p>
        </div>

        <h2>{{item.title}}</h2>
        {% if item.photos.all %}
            <p><img class="img-article-left thumb" src="{{ item.photos.first.photo.url }}" alt="photo"></p>
        {% endif %}
        <p>Размеры: {{item.size}}</p>
        <p>{{item.description|linebreaks|truncatewords:50}}</p>
            <div class="clear"></div>
            <p class="link-read-post"><a href="{{ item.get_absolute_url }}">Подробнее</a></p>
    </li>
    {% endfor %}
</ul>

{% endblock %}

shopsite/shopapp/templates/shop/edit_profile.html
{% extends 'shop/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Подтвердить</button>
    <p class="link-read-post"><a href="{% url change_password.url_name %}">{{change_password.title}}</a></p>
</form>
 
{% endblock %}

shopsite/shopapp/templates/shop/favorite_list.html
{% extends 'shop/base.html' %}

{% block content %}
<ul class="list-articles">
    {% for item in favor_list %}
    <li> 
        <h2>{{item.title}}</h2>
        {% if item.photos.all %}
            <p><img class="img-article-left thumb" src="{{ item.photos.first.photo.url }}" alt="photo"></p>
        {% endif %}
        <p>Размеры: {{item.size}}</p>
        <p>Цена: {{item.price}} $</p>
        <form action="{% url 'favorites:remove' id=item.id %}" method="POST"> {% csrf_token %}
            <input type="hidden" name="id" value="{{ item.id }}">
            <input type="hidden" name="url_from" value="{{ request.path }}">
            <button type="submit" class="favor del">Удалить из избранного</button>
        </form>
        <div class="clear"></div>
            <p class="link-read-post"><a href="{{ item.get_absolute_url }}">Подробнее</a></p>
    </li>
    {% endfor %}
</ul>
{% endblock %}

shopsite/shopapp/templates/shop/item.html
{% extends 'shop/base.html' %}

{% block content %}
<h1>{{item.title}}</h1>
{% for photo in item.photos.all %}
    {% if forloop.counter0|divisibleby:3 %}
        <div class="row">
    {% endif %}

    <div class="col">
        <img class="img-article-left" src="{{ photo.photo.url }}" alt="photo">
    </div>

    {% if forloop.counter|divisibleby:3 or forloop.last %}
        </div>
    {% endif %}
{% endfor %}


<p>Размеры: {{item.size}}</p>
<p>Доступное количество: {{item.count}}</p>
<p>Цена: {{item.price}} $</p>

{% if item.discount %}
    <p>Скидка: {{item.discount}} %</p>
    <p>Цена со скидкой: {{ item.price_with_discount|floatformat }}</p>
{% endif %}

<p>Описание: {{item.description|linebreaks}}</p>
<p>Дата добавления товара: {{item.time_update|date:"d-m-Y"}}</p>

<!-- Функционал добавления в избранное -->
<!-- если товар еще не добавлен в избранное то отображаем кнопку добавления -->
    {% if is_notfavorite %}
    <form action="{% url 'favorites:add' id=item.id %}" method="POST"> {% csrf_token %}
    <!-- конструкция favorites:add добавляет пространство имен favorites, которе было определено в юрлах приложения favorites
    app_name ='favorites', таким образом получаем доступ к функции add_to_favorites имя 
    которой в юрлах указанно как name = 'add'
    запись id=item.id передает в функцию представления аргумент id-->
        <!-- сркытно передаем id товара и путь откуда был добавлен товар -->
        <input type="hidden" name="id" value="{{ item.id }}">
        <input type="hidden" name="url_from" value="{{ request.path }}">
        <button type="submit" class="favor add">Добавить в избранное</button>
    </form>
<!-- если товар уже добавлен в избранное, то отображаем кнопку удаления из избранного -->
    {% else %}
    <form action="{% url 'favorites:remove' id=item.id %}" method="POST"> {% csrf_token %}
        <input type="hidden" name="id" value="{{ item.id }}">
        <input type="hidden" name="url_from" value="{{ request.path }}">
        <button type="submit" class="favor del">Удалить из избранного</button>
    </form>
    {% endif %}

{% endblock %}

shopsite/shopapp/templates/shop/login.html
{% extends 'women/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Войти</button>
</form>
 
{% endblock %}